In [1]:
import numpy as np

1. How to add a border (filled with 0's) around an existing array?

In [3]:
array = np.ones((3,3))

print(array)
array = np.pad(array, pad_width=1, mode='constant',
               constant_values=0)

print(array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


2. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [4]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

3. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
matrix = np.zeros((5, 5))

values = [1, 2, 3, 4]
for t, value in enumerate(values, start=1):
    matrix[t, t-1] = value

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


4. Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
x = np.ones((3, 3))

print("Checkerboard pattern:")

x = np.zeros((8, 8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)


Checkerboard pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


5. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [8]:
shape = (6, 7, 8)

index = np.unravel_index(99, shape)

print("Index (x, y, z) of the 100th element:", index)


Index (x, y, z) of the 100th element: (1, 5, 3)


6. Create a checkerboard 8x8 matrix using the tile function

In [9]:
checkerboard_pattern = np.array([[0, 1], [1, 0]])


checkerboard_matrix = np.tile(checkerboard_pattern, (4, 4))

print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


7. Normalize a 5x5 random matrix

In [10]:
matrix = np.random.random((5, 5))

matrix_mean = np.mean(matrix)
matrix_std_dev = np.std(matrix)

#To normalize a matrix means to scale its values so that they fall within a specific range or follow a certain distribution. One common normalization technique is to rescale the values to have a mean of 0 and a standard deviation of 1, also known as z-score normalization.
normalized_matrix = (matrix - matrix_mean) / matrix_std_dev

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.45386937 0.77626609 0.19823701 0.61592963 0.02091652]
 [0.67953466 0.51183264 0.34479418 0.35989424 0.88090446]
 [0.02899326 0.85549336 0.41316402 0.01816103 0.46988444]
 [0.18152919 0.79899927 0.81321921 0.56271541 0.76645924]
 [0.05742296 0.3730293  0.01228334 0.33326951 0.79502182]]

Normalized Matrix:
[[ 0.00344158  1.11700124 -0.8795137   0.56319842 -1.49197944]
 [ 0.78289046  0.20364698 -0.37330458 -0.32114893  1.47842261]
 [-1.46408232  1.39065257 -0.13715487 -1.5014969   0.0587577 ]
 [-0.93722256  1.19552174  1.24463748  0.37939628  1.08312833]
 [-1.36588602 -0.27578037 -1.52179848 -0.41311086  1.18178363]]


8. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [13]:
dtype_rgba = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])

colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)],dtype=dtype_rgba)
print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [14]:
x = np.random.random((5,3))

print("First array:")
print(x)

y = np.random.random((3,2))

print("Second array:")
print(y)


z = np.dot(x, y)

print("Dot product of two arrays:")
print(z)

First array:
[[0.44657147 0.41306929 0.22321749]
 [0.78133984 0.8266446  0.06551802]
 [0.90648021 0.39585435 0.64609154]
 [0.01432908 0.07084149 0.55416029]
 [0.76917448 0.62440375 0.5854627 ]]
Second array:
[[0.13472302 0.85626623]
 [0.82055511 0.58843921]
 [0.02491621 0.04934643]]
Dot product of two arrays:
[[0.40467131 0.63646523]
 [0.78520438 1.1586981 ]
 [0.46304222 1.04100693]
 [0.07386738 0.08130125]
 [0.63057072 1.05493228]]


10. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [16]:
array = np.array([1, 5, 4, 9, 7, 2, 6, 3, 8, 10])

indices = np.where((array > 3) & (array < 8))

array[indices] *= -1

print("Modified Array:", array)


Modified Array: [ 1 -5 -4  9 -7  2 -6  3  8 10]


11. What is the output of the following script?

In [17]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


12. Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
These are legal

13. What are the result of the following expressions?

np.array(0) / np.array(0) = This expression will raise a runtime warning or error indicating division by zero.

np.array(0) // np.array(0) = This expression will raise a runtime warning or error indicating division by zero.

np.array([np.nan]).astype(int).astype(float) = This expression converts a numpy array containing a NaN (Not a Number) value to an integer type and then back to a float type. When you convert a NaN value to an integer, it becomes 0, and then when you convert it back to a float, it remains 0.0. So, the resulting array will be array([0.]).

14. How to round away from zero a float array ?

In [21]:
array = np.array([-2.5, -1.8, 0.3, 1.5, 2.7])

result = np.ceil(array)

print(result)

[-2. -1.  1.  2.  3.]


15. How to find common values between two arrays?

In [22]:
array1 = np.array([0, 10, 20, 40, 60])

print("Array1: ", array1)

array2 = [10, 30, 40]

print("Array2: ", array2)

print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]
