1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [3]:
np.__version__

'1.25.2'

3. Create a null vector of size 10

In [7]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array

In [10]:
arr = np.array([2,3,4,1,8,9])
memory_size_bytes = arr.nbytes

print(memory_size_bytes)

48


5. How to get the documentation of the numpy add function from the command line?

In [ ]:
python -c "import numpy; help(numpy.add)"


6. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
null_vector = np.zeros(10)
null_vector [4]= 1
print(null_vector)


7. Create a vector with values ranging from 10 to 49

In [22]:
vector = np.arange(10,49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


8. Reverse a vector (first element becomes last)

In [26]:
vector = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

reversed_vector = vector[::-1]
print(reversed_vector)

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [33]:
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [35]:
elements = [1,2,0,0,4,0]

nonzero_elements= np.nonzero(elements)
print(nonzero_elements)

(array([0, 1, 4]),)


11. Create a 3x3 identity matrix

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values

In [42]:
values= np.random.rand(3,3,3)
print(values)

[[[0.23753611 0.1723402  0.70134149]
  [0.10292656 0.1542785  0.5366897 ]
  [0.04738314 0.45134533 0.6660394 ]]

 [[0.74593436 0.74731878 0.15321543]
  [0.93211699 0.55242172 0.8840386 ]
  [0.07502203 0.36431202 0.17181178]]

 [[0.48137814 0.21646203 0.69837579]
  [0.04818996 0.44494454 0.74772532]
  [0.06202232 0.61081667 0.92371986]]]


13. Create a 10x10 array with random values and find the minimum and maximum values

In [43]:
values= np.random.rand(10,10)

min_value = values.min()
max_value = values.max()

print(min_value)
print(max_value)

0.02006875996760049
0.9972663209867386


14. Create a random vector of size 30 and find the mean value

In [44]:
vector = np.random.rand(30)
mean_vector = vector.mean()

print(mean_vector)

0.5160155222293352


15. Create a 2d array with 1 on the border and 0 inside

In [46]:
import numpy as np

rows, cols = 5, 5

array = np.zeros((rows, cols))

array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
