In [4]:
import numpy as np

1. How to ignore all numpy warnings?

In [ ]:
old_settings = np.seterr(all='ignore')

np.seterr(**old_settings)


2. Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)


They arent the same np.sqrt(-1) is mainly used for 'real' numbers while np.emath.sqrt(-1) is meant for complex numbers so it returns the square root.

3.

In [ ]:
from datetime import datetime, timedelta

today = datetime.now().date()

yesterday = today - timedelta(1)

tomorrow = today + timedelta(1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-02-19
Today: 2024-02-20
Tomorrow: 2024-02-21


4. How to get all the dates corresponding to the month of July 2016?

In [ ]:

print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


5. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [ ]:
import numpy as np


A = np.array([1, 2, 3])
B = np.array([4, 5, 6])


np.add(A, B, out=A)
np.multiply(A, -A / 2, out=A)

# Result stored in A
print(A)


6. Extract the integer part of a random array of positive numbers using 4 different methods

In [ ]:
random_array = np.random.rand(5) * 10

integer_part_floor = np.floor(random_array)

integer_part_ceil = np.ceil(random_array)

integer_part_cast = random_array.astype(int)

integer_part_bitwise = random_array & 0xFFFFFFFFFFFFFFF0

# Print the results
print("Original Array:", random_array)
print("Integer Part (Floor):", integer_part_floor)
print("Integer Part (Ceil):", integer_part_ceil)
print("Integer Part (Cast):", integer_part_cast)
print("Integer Part (Bitwise):", integer_part_bitwise)


7. Create a 5x5 matrix with row values ranging from 0 to 4

In [ ]:
matrix = np.arange(5).reshape(-1, 1) + np.arange(5)

print(matrix)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


8. Consider a generator function that generates 10 integers and use it to build an array

In [5]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


9. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [6]:
V = np.linspace(0,1,12,endpoint=True)[1:-1]
print(V)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


10. Create a random vector of size 10 and sort it

In [7]:
i = np.random.random(10)
i.sort()
print(i)

[0.01536492 0.12661055 0.25515878 0.29316453 0.3776484  0.46605525
 0.48764948 0.71714744 0.83676998 0.92359163]


11. How to sum a small array faster than np.sum?

In [8]:
small_array = np.array([1, 2, 3, 4, 5])

result = sum(small_array)

print(result)


15


12. Consider two random array A anb B, check if they are equal

In [9]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


13. Make an array immutable (read-only)

In [12]:
Z = np.zeros(10)
Z.flags.writeable = False
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


14. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [13]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.69194381 0.85117245 0.24111108 0.89713305 0.79904861 0.87539558
 0.97429882 0.69498276 1.19892615 0.86455278]
[0.77147092 0.18697809 1.07850471 0.21444515 0.99723116 1.11639116
 0.27046561 0.67365724 0.88834191 1.32505195]


15. Create random vector of size 10 and replace the maximum value by 0

In [14]:
t = np.random.random(10)
t[T.argmax()] = 0
print(t)

[0.38801672 0.72760969 0.85817925 0.14604422 0.78900974 0.52947807
 0.08174366 0.72815376 0.00689537 0.        ]
