In [2]:
import numpy as np

1. Find the nearest value from a given value in an array

In [8]:
Z = np.random.uniform(0,1,10)
z = 0.5
n = Z.flat[np.abs(Z - z).argmin()]
print(n)

0.5218582255939791


2. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [9]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


3. Create an array class that has a name attribute

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

r = NamedArray(np.arange(10), "range_10")
print (r.name)

4. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
y = np.ones(10)
I = np.random.randint(0,len(y),20)
np.add.at(y, I, 1)
print(y)


[1. 4. 2. 4. 4. 2. 3. 2. 5. 3.]


5. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [13]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


6. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [14]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


7. Considering a four dimensions array, how to get sum over the last two axis at once?

In [16]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[51 50 57 59]
 [73 39 77 71]
 [36 61 57 45]]


8. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [17]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[0.57201046 0.5945813  0.36231357 0.42572621 0.4706866  0.53125028
 0.42442124 0.72383097 0.60528869 0.44924334]


9. How to get the diagonal of a dot product?

In [19]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.sum(A * B.T, axis=1)

array([0.63439137, 1.70840238, 0.86366345, 0.91485224, 1.4372927 ])

10. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [24]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


11. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [25]:
X = np.ones((5,5,3))
Y = 2*np.ones((5,5))
print(X * Y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


12. How to swap two rows of an array?

In [26]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

array[0], array[1] = array[1], array[0]

print("Array after swapping rows:")
print(array)


Array after swapping rows:
[[4 5 6]
 [4 5 6]
 [7 8 9]]


13. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [27]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 15) ( 3, 43) ( 9, 61) ( 9, 75) (15, 43) (20, 53) (20, 90) (21, 63)
 (21, 90) (26, 48) (26, 66) (27, 37) (27, 95) (30, 57) (30, 65) (31, 44)
 (31, 45) (37, 95) (44, 45) (44, 59) (44, 90) (48, 66) (53, 90) (57, 65)
 (59, 90) (61, 75) (63, 90) (66, 72) (66, 80) (72, 80)]


14. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [28]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


15. How to compute averages using a sliding window over an array?

In [29]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


16. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [30]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


17. How to negate a boolean, or to change the sign of a float inplace?

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

18. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

19. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

20. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

Still working on it.

21. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [31]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


22. Compute a matrix rank

In [32]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:", rank)


Rank of the matrix: 2


23. How to find the most frequent value in an array?

In [33]:
array = np.array([1, 2, 3, 2, 2, 3, 4, 2, 5, 2])

counts = np.bincount(array)

most_frequent_value = np.argmax(counts)

print("Most frequent value:", most_frequent_value)


Most frequent value: 2


24. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [34]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 1 1]
   [4 3 1]
   [2 1 2]]

  [[1 1 0]
   [3 1 0]
   [1 2 2]]

  [[1 0 2]
   [1 0 4]
   [2 2 1]]

  [[0 2 0]
   [0 4 4]
   [2 1 2]]

  [[2 0 1]
   [4 4 2]
   [1 2 4]]

  [[0 1 3]
   [4 2 3]
   [2 4 3]]

  [[1 3 0]
   [2 3 2]
   [4 3 1]]

  [[3 0 2]
   [3 2 1]
   [3 1 0]]]


 [[[4 3 1]
   [2 1 2]
   [3 2 4]]

  [[3 1 0]
   [1 2 2]
   [2 4 2]]

  [[1 0 4]
   [2 2 1]
   [4 2 3]]

  [[0 4 4]
   [2 1 2]
   [2 3 3]]

  [[4 4 2]
   [1 2 4]
   [3 3 2]]

  [[4 2 3]
   [2 4 3]
   [3 2 2]]

  [[2 3 2]
   [4 3 1]
   [2 2 4]]

  [[3 2 1]
   [3 1 0]
   [2 4 2]]]


 [[[2 1 2]
   [3 2 4]
   [1 2 3]]

  [[1 2 2]
   [2 4 2]
   [2 3 3]]

  [[2 2 1]
   [4 2 3]
   [3 3 4]]

  [[2 1 2]
   [2 3 3]
   [3 4 4]]

  [[1 2 4]
   [3 3 2]
   [4 4 4]]

  [[2 4 3]
   [3 2 2]
   [4 4 1]]

  [[4 3 1]
   [2 2 4]
   [4 1 3]]

  [[3 1 0]
   [2 4 2]
   [1 3 4]]]


 [[[3 2 4]
   [1 2 3]
   [4 2 1]]

  [[2 4 2]
   [2 3 3]
   [2 1 2]]

  [[4 2 3]
   [3 3 4]
   [1 2 1]]

  [[2 3 3]
   [3 4 4]
   [2 1 2]]

  [[3 3 2]
   

25. Create a 2D array subclass such that Z[i,j] == Z[j,i]

Still working on it.

26. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

I cant work my way around this one, still working on it.

27. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [3]:
a = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], k), axis=0),
                                       np.arange(0, a.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


28. How to implement the Game of Life using numpy arrays?

29. How to get the n largest values of an array

In [4]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995]


30. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [5]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


31. How to create a record array from a regular array?

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

32. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [ ]:
Z = np.random.randint(1, 10, size=(1000000,))

result1 = Z ** 3

result2 = np.power(Z, 3)

result3 = np.empty_like(Z)
for i in range(len(Z)):
    result3[i] = Z[i] **3
assert np.array_equal(result1, result2) and np.array_equal(result2, result3)

print("Results are equal.")


33. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

Didnt manage this one still working on it.

34. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [6]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 7, 7],
                   [2, 2, 2],
                   [3, 3, 3],
                   [4, 4, 4],
                   [5, 6, 7],
                   [8, 8, 8],
                   [9, 9, 9],
                   [10, 11, 12]])


unequal_rows = matrix[np.apply_along_axis(lambda row: len(np.unique(row)) > 1, axis=1, arr=matrix)]

print("Rows with unequal values:")
print(unequal_rows)


Rows with unequal values:
[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [10 11 12]]


35. Convert a vector of ints into a matrix binary representation

In [7]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


36. Given a two dimensional array, how to extract unique rows?

In [8]:

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])

unique_rows = np.unique(array, axis=0)

print("Unique rows:")
print(unique_rows)


Unique rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


37. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

38. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

39. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

40. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [9]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.07322329  0.28946104]
